name: Check Branch & Commit Conventions

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch and commit message
        run: |
          # Check each commit message
          git log origin/main..HEAD --pretty=format:"%s" | while read -r COMMIT_MSG; do
            if ! [[ "$COMMIT_MSG" =~ ^#[0-9]+:\ .* ]]; then
              echo "ERROR: Commit message '$COMMIT_MSG' is invalid."
              echo "Expected format: '#<issue number>: message'"
              exit 1
            fi
          done
